import Head from "next/head";
import Image from "next/image";
import Copyright from "@/components/copyright";
import Footer from "@/components/footer";
import Carousel from "react-bootstrap/Carousel";
import Other_banner from "@/components/other_banner";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Carte_pour_livre from "@/components/collection_congolaise";
import Navbar from "@/components/header";
import Link from "next/link";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export default function detai_livre({ livres, auteur }) {
  return (
    <>
      <Head>
        <title>livraze </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo-livraze.png" />
      </Head>
      <main className={styles.main}>
        <Navbar />

        <div className="collections_list">
          <div className="section_une">
            <div className="auteur_infos">
              <div className="avatar">
                <img
                  className="img_autors"
                  src={`http://livraze-admin.ritach.net/Views/uploads-images/auteurs/${auteur.avatar}`}
                  alt={auteur.legende}
                />

                <span>
                  <i>{auteur.legende}...</i>
                </span>
                {/* <Image
                  src="/livraze_add.jpg"
                  className="img_autors"
                  alt=""
                  layout="fill"
                  objectFit="contain"
                /> */}
              </div>
              <div className="bio">
                <h3> {auteur.nom}..</h3>
                <p>{auteur.bio}..</p>
              </div>
            </div>

            {/* <div className="voir_aussi"> Voir aussi </div> */}
            {/* <div className="cards_container ">
                {livres?.livres?.slice(0, 5)?.map((item, index) => (
                  <Link href={`${item.id}`}>
                    <Carte_pour_livre
                      key={index}
                      nom_auteur={item.auteur}
                      auteur_img_src="/icons/ecrivain.png"
                      titre_l={item.titre}
                      livre_img_src={`${url_img}${item.couverture}`}
                    />
                  </Link>
                ))}
              </div> */}
          </div>

          <div className="section_deux">
            <div className="carousel_collections">
              <Link href="">
                <Image
                  src="/livraze_add.jpg"
                  className="caroussels_img"
                  alt="Picture of the author"
                  width={180}
                  height={200}
                  priority
                />
              </Link>
            </div>
            <div className="categories">
              <h3> Plus consultés </h3>
              <ul>
                {livres?.livres?.slice(0, 5)?.map((item, index) => (
                  <Link href={`../livres/${item.id}`}>
                    <li>{item.titre} → </li>
                  </Link>
                ))}
              </ul>
            </div>
          </div>
        </div>
        <div className="voir_aussi">
          {" "}
          <h5> Vous pouvez aimer ceci aussi</h5>
        </div>
        <div className="cards_container">
          {livres?.livres?.slice(0, 9)?.map((item, index) => (
            <Link href={`../livres/${item.id}`}>
              <Carte_pour_livre
                key={index}
                nom_auteur={item.auteur}
                auteur_img_src="/icons/ecrivain.png"
                titre_l={item.titre}
                livre_img_src={`http://livraze-admin.ritach.net/Views/uploads-images/nos_livres/${item.couverture}`}
              />
            </Link>
          ))}
        </div>

        <div className="toutes_les_collections">
          <Link href="../collection-congolaise">Autres collections →</Link>
        </div>

        <Footer />
        <Copyright />
      </main>
    </>
  );
}

export const getServerSideProps = async ({ params }) => {
  const router = params;
  const { nom } = router;

  const request_for_unique = await fetch(
    `http://livraze-admin.ritach.net/api-v1?auteur=${nom}`
  );
  const resquest_for_all_books = await fetch(
    "http://livraze-admin.ritach.net/api-v1?datas=livres_all"
  );

  const auteur = await request_for_unique.json();
  const livres = await resquest_for_all_books.json();
  console.log("auteur: ", auteur);
  return {
    props: {
      auteur,
      livres,
    },
  };
};
