import Head from "next/head";
import Image from "next/image";
import Copyright from "../components/copyright";
import Footer from "../components/footer";
import Navbar from "../components/header";
import Other_banner from "@/components/other_banner";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Item_top_5 from "@/components/compsants_standards";
import List_items from "@/components/List_items";
import Nav_bar from "../components/navbar";
import Link from "next/link";

// const inter = Inter({ subsets: ["latin"] });

export default function apropos() {
  return (
    <>
      <Head>
        <title>livraze </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo-livraze.png" />
      </Head>
      <main className={styles.main}>
        <Navbar />
        <Other_banner
          un="Un livre ne tombe jamais en panne  "
          deux_n="mais un smartphone oui"
        ></Other_banner>
        <div className={styles.default_div}>
          <p>
            Livraze est une bibliothèque privée de l'agence de communication
            globale Fidba Graphics. Avec des collections variées dans tous les
            domaines qui intéressent ses abonnés, la bibliothèque Livraze a
            marié la compétence des nouvelles technologies dans ses techniques
            d'approche afin d'encourager les jeunes à lire. Une bibliothèque
            jeune, moderne et riche avec des collections intéressantes qui font
            rêver ses abonnés.La bibliothèque Livraze, étant la toute première
            bibliothèque privée et moderne de la ville touristique de Goma, a
            mis en avant les besoins de ses abonnés en leur laissant le choix de
            consulter les documents ou les livres sur place ou de les emprunter.
            UN LIVRE NE TOMBE JAMAIS EN PANNE, UN SMARTPHONE OUI. À l'ère du
            numérique, où la plupart des jeunes sont perdus dans le flux
            d'informations et d'intoxication, de vidéos moins productives sur
            TikTok et Instagram, de vidéos pornographiques facilement
            accessibles sur internet, l'envoi de sextapes sur des plateformes de
            messagerie comme WhatsApp, alors Livraze, la bibliothèque la plus
            proche de ses abonnés, se concentre sur l'initiation des jeunes à la
            lecture, une lecture sûre, sans piles à recharger ou à casser, sans
            tabou, une lecture informative, une lecture sur papier. Et ce, afin
            que les jeunes restent concentrés sur l'essentiel, pour leur bien et
            celui de nos communautés.
          </p>
          <h3 className={styles.subtitle_n}>Mission</h3>
          Livraze est une bibliothèque privée de l'agence de communication
          globale Fidba Graphics. Avec des collections variées dans tous les
          domaines qui intéressent ses abonnés, la bibliothèque Livraze a marié
          la compétence des nouvelles technologies dans ses techniques
          d'approche afin d'encourager les jeunes à lire. Une bibliothèque
          jeune, moderne et riche avec des collections intéressantes qui font
          rêver ses abonnés.La bibliothèque Livraze, étant la toute première
          bibliothèque privée et moderne de la ville touristique de Goma, a mis
          en avant les besoins de ses abonnés en leur laissant le choix de
          consulter les documents ou les livres sur place ou de les emprunter.
          UN LIVRE NE TOMBE JAMAIS EN PANNE, UN SMARTPHONE OUI. À l'ère du
          numérique, où la plupart des jeunes sont perdus dans le flux
          d'informations et d'intoxication, de vidéos moins productives sur
          TikTok et Instagram, de vidéos pornographiques facilement accessibles
          sur internet, l'envoi de sextapes sur des plateformes de messagerie
          comme WhatsApp, alors Livraze, la bibliothèque la plus proche de ses
          abonnés, se concentre sur l'initiation des jeunes à la lecture, une
          lecture sûre, sans piles à recharger ou à casser, sans tabou, une
          lecture informative, une lecture sur papier. Et ce, afin que les
          jeunes restent concentrés sur l'essentiel, pour leur bien et celui de
          nos communautés.
          <h3 className={styles.subtitle_n}>Notre Histoire</h3>
          Livraze a été fondée au mois d’avril 2022, à l'initiative de Fidel
          BASHIGE, le PDG de Fidba Graphics. Cette idée de bibliothèque remonte
          à plusieurs années mais elle est devenue une réalité en décembre 2022
          lorsque ses collections ont atteint un niveau record, où 1000 abonnés
          pouvaient emprunter des livres sans que les étagères restent vides. Le
          grand défi au départ était que nous n'avions pas de livres. Seulement
          quelques dizaines et qui ne devaient pas répondre au grand besoin que
          nous ressentions : servir la ville de Goma en général. Aujourd'hui, la
          bibliothèque Livraze vise l'excellence dans la promotion de la lecture
          auprès d'une catégorie d'abonnés âgés de 13 ans et plus. Nous,
          Livraze, sommes passionnés par les livres depuis longtemps. Cette
          envie de lire ne devait pas rester uniquement la nôtre, alors un jour
          de l'année 2021, nous avons pensé à créer une bibliothèque physique,
          moderne et innovante. En avril 2022, nous avions mis en place une
          stratégie qui consistait à acheter des livres d'occasion en échange
          d'une somme d'argent selon les négociations avec les particuliers qui
          les échangeaient avec nous. Au bout de quelques jours, nous avions
          récolté une cinquantaine de livres, et le rêve commençait à prendre de
          l'ampleur. En décembre 2022, l'histoire retiendra que cette année-là,
          nous avons acheté des livres, en mettant de côté la peur d'échouer, à
          des revendeurs qui avaient en leur possession des ouvrages aux sujets
          très intéressants. Nous sommes passés de 400, à 700, à 1235 et le
          nombre de livres n'a cessé d'augmenter plus vite que les battements de
          cœur d'une musaraigne pygmée connue pour avoir le cœur le plus rapide
          du règne animal : aussi étonnant que cela puisse paraître, le cœur de
          ce petit rongeur bat à la vitesse impressionnante de 1000 battements
          par minute, soit 16 battements par seconde. C'est exceptionnel pour un
          si petit animal. Notre histoire peut devenir la vôtre ! Nous avons
          franchi le pas, pour ouvrir pour vous la bibliothèque la plus
          intelligente de la ville de Goma. Alors c'est à vous, bien sûr vous,
          d'apporter votre contribution pour que nous atteignions 1000 abonnés.
          Choisissez l'offre qui vous convient le mieux. Abonnez-vous ici
          Soirées littéraires
          <br />
          <br />
          <br />
          <a className="Voir_toutes_nos_collections" href="">
            En savoir plus sur la soirée littéraire →
          </a>
        </div>

        <Footer> </Footer>
        <Copyright> </Copyright>
      </main>
    </>
  );
}
