import Head from "next/head";
import Image from "next/image";
import Copyright from "../components/copyright";
import Footer from "../components/footer";
import Navbar from "../components/header";
import Other_banner from "@/components/other_banner";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Item_top_5 from "@/components/compsants_standards";
import List_items from "@/components/List_items";
import Link from "next/link";
import Nav_bar from "../components/navbar";

// const inter = Inter({ subsets: ["latin"] });

export default function concours() {
  return (
    <>
      <Head>
        <title>livraze </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo-livraze.png" />
      </Head>
      <main className={styles.main}>
        <Navbar />
        <Other_banner
          title="Concours"
          subtitle="Nous somme la bibliothèque la plus moderne dans la ville"
          action="Participer"
        ></Other_banner>
        <div className={styles.default_div}>
          Le concours livraze est un concours qui vise à récompenser 4 lauréats
          ayant lu et pouvant commenter en public une œuvre d'un auteur local ou
          national proposé par les organisateurs. L'objectif de ce concours est
          de stimuler le goût de la lecture dans les universités et de vendre
          des œuvres locales aux jeunes.
          <h3 className={styles.subtitle_n}>
            Les lauréats du concours seront récompensés par 4 prix :
          </h3>
          <ul>
            <li>Première place : 600 000 fc</li>

            <li>Deuxième place : 400 000 fc</li>

            <li>Troisième place : 200 000 fc</li>

            <li>
              Quatrième prix : 2 mois d'abonnement à la bibliothèque livraze.
            </li>
          </ul>
          <i> Il n'y a pas de frais de participation. </i>
          <h3 className={styles.subtitle_n}>
            Conditions de participation au concours{" "}
          </h3>
          <ul>
            <li>Avoir entre 16 et 30 ans </li>

            <li> Etre de nationalité congolaise </li>

            <li> Résider à Goma </li>

            <li>
              {" "}
              Présenter une carte d'étudiant de l'une des institutions ou
              universités de Goma.{" "}
            </li>

            <li>
              {" "}
              Soumettre la candidature dans le délai fixé par l'organisation.
            </li>

            <li> Avoir un compte Instagram et un profil Facebook </li>

            <li>
              {" "}
              Être actif sur WhatsApp pendant toute la durée du concours.
            </li>
          </ul>
          <h3 className={styles.subtitle_n}>
            {" "}
            Directives pour les participants au concours{" "}
          </h3>
          <ol>
            <li>
              {" "}
              Livraze ne demande aucune commission ou argent aux participants
              pendant toute la durée du concours, des éliminations à la grande
              finale. Les 100 premières participations seront sélectionnées pour
              passer aux phases des éliminations
            </li>

            <li>
              Les 4 canaux de communication utilisés par Livraze sont les
              suivants :
              <ul>
                <li>
                  L'adresse e-mail concours@livraze.com (pour accuser réception
                  de la candidature de l'étudiant et encourager les participants
                  qui n'ont pas atteint la finale).
                </li>
                <li>
                  Le groupe WhatsApp géré par l'administration de Livraze dans
                  lequel sont réunis tous les participants du concours.
                </li>
                <li>
                  Les réseaux sociaux Instagram, Facebook, Twitter et Linkedin
                  Livraze.
                </li>
                <li>Le site officiel www.livraze.com </li>
              </ul>
            </li>
          </ol>
          <i>
            NB : seul le numéro mentionné ici a le pouvoir de contacter les
            participants sur appel normal ou WhatsApp au sujet du concours.
          </i>
          <h3 className={styles.subtitle_n}>Étapes du processus du concours</h3>
          Les éliminations sont divisées en 4 grandes étapes après réception des
          candidatures des élèves.
          <ul>
            <li>
              Étape 0 : L'enregistrement des candidatures sera ouvert pendant
              une période de 7 jours.
            </li>
            <li>
              Étape 1 : Après avoir reçu toutes les candidatures pendant une
              semaine, les organisateurs publient la liste complète des 100
              candidats sur les réseaux sociaux de Livraze et dans le groupe
              WhatsApp dans lequel se trouvent tous les participants.
            </li>
            <br />
            Le 8e jour du concours, le compte à rebours est lancé sur les
            réseaux sociaux Facebook et Instagram de Livraze enjoignant les
            participants au concours à inviter leurs amis et leur famille à
            aimer et partager leur post publié sur la page Facebook officielle
            de Livraze ou à aimer leur post sur le compte Instagram officiel de
            Livraze. 100 likes sur Facebook représentent 1 % et 100 partages
            représentent 1 %. 100 likes sur Instagram représentent 1,5%. Le vote
            sur les réseaux sociaux dure au maximum 48 heures.
            <h5>Phase d'élimination 1 :</h5>
            Le 11e jour du concours, les résultats des réseaux sociaux seront
            publiés le matin sur toutes les plateformes numériques de Livraze.
            <br />
            Remarque : Les résultats du vote sur les réseaux sociaux
            représentent 15 % des points du concours. Seuls 50 étudiants ayant
            obtenu plus de % passeront à l'étape 2 du concours. La liste de
            leurs noms sera partagée sur les plateformes de communication de
            Livraze et celles de ses partenaires.
            <br />
            <li>
              Etape 2 : Les participants présélectionnés au concours Livraze
              recevront le titre d'un livre d'un auteur local ou national. Le
              livre sera lu pendant une période de 5 jours.
            </li>
            <i>
              NB : Si l'étudiant a déjà un abonnement actif à la bibliothèque,
              il ne pourra pas payer à nouveau l’abonnement.
            </i>
            <h5>Phase d'élimination 2 :</h5>
            <li>
              Etape 3 : Travail en équipe : le 17ème jour du concours, les 50
              candidats seront regroupés en 5 équipes de 10 étudiants chacune
              pour présenter le sujet du livre. Chaque équipe représentera un
              team leader pour défendre son groupe devant le jury Alpha du
              concours.
            </li>
            <br />
            Le jury procédera ensuite aux questions-réponses en partageant avec
            chaque groupe un chapitre du livre dont sera tiré le questionnaire.
            Tous les membres du groupe sont autorisés à participer à la séance
            de questions-réponses qui aura lieu dans les salons VIP 2 de
            l'agence de communication FIDBA GRAPHICS devant quelques invités et
            partenaires. NB : La présentation représente 40% des points du
            concours. Ces points sont répartis équitablement entre les membres
            de l'équipe. A ce niveau, l'étudiant qui n'aura pas lu le travail ou
            qui sera absent sans raison valable lors de la séance de
            questions-réponses sera automatiquement éliminé. A l'issue de cette
            session, la liste des candidats sélectionnés pour la deuxième phase
            d'élimination sera publiée sur les plateformes de communication de
            Livraze et de ses partenaires.
            <br />
            Les points récoltés lors de la première phase d'élimination seront
            ajoutés à ceux de la deuxième phase d'élimination pour déterminer le
            % d’étudiants qui seront sectionnés. Seuls 25 élèves passeront à
            l'étape suivante du concours et la liste sera publiée après 24
            heures de l'étape 3 du concours.
            <h5>Phase d'élimination 3</h5>
            SEMI-FINALE Soutien du public des candidats : Le 19e jour du
            concours, les 25 candidats recevront chacun un crédit de 20 billets
            de 5 dollars chacun afin d'encourager leurs amis et leur famille à
            venir assister à leur prestation en demi-finale. Chaque ticket vendu
            représente 0,5% des points.
            <li>Etape 4 : Concours de rédaction : </li>
            Le 21ème jour du concours, les 25 participants présélectionnés
            seront invités avec leur public à passer un test d'orthographe dans
            la salle de formation A et B de l'agence de communication Fidba
            Graphics. Les 25 participants seront répartis en 5 groupes de 5,
            trois personnes de chaque groupe seront éliminées en direct après la
            correction du jury Alpha. NB : chaque erreur représente 1,8% en
            moins. Chaque rature représente 0,6% en moins.
            <br />
            <b>
              <i>
                Les 10 Candidats présélectionnés lors de la troisième phase
                d'éliminations seront publiés en temps réel sur les réseaux
                sociaux de Livraze.
              </i>
            </b>
            <br />
            Petite FINALE
            <li>
              Etape 5 : Le 22e jour du concours, les Candidats présélectionnés
              recevront chacun 20 crédits de billets d'entrée de 10 $ chacun
              afin d'inciter leur public à assister à leur spectacle de grande
              finale. Chaque billet vendu représente 0,5 % des points. En
              fonction des ventes de billets, 4 candidats seront éliminés 4
              jours après cette étape.
            </li>
            GRANDE FINALE
            <li>
              Etape 5 : Le 28ème jour du concours, les 6 candidats
              s'affronteront devant un jury, 4 d'entre eux recevront les prix
              des 4 meilleurs étudiants du concours Livraze Student.
            </li>
          </ul>{" "}
          La finale aura lieu dans un hôtel local.
          <br />
          <br />
          <br />
          <div className={styles.call_to_action_n}>
            <a
              href="presentationSoireeLitteraire/"
              className="Voir_toutes_nos_collections"
            >
              Voir aussi la soirée littéraire →
            </a>
          </div>
        </div>

        <Footer> </Footer>
        <Copyright> </Copyright>
      </main>
    </>
  );
}
