import Head from "next/head";
import Image from "next/image";
import Copyright from "../components/copyright";
import Footer from "../components/footer";
import Navbar from "../components/header";
import Other_banner from "@/components/other_banner";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Item_top_5 from "@/components/compsants_standards";
import List_items from "@/components/List_items";
import Nav_bar from "../components/navbar";
import Link from "next/link";

// const inter = Inter({ subsets: ["latin"] });

export default function partenariat() {
  return (
    <>
      <Head>
        <title>livraze </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo-livraze.png" />
      </Head>
      <main className={styles.main}>
        <Navbar />
        <Other_banner
          title="Partenariat"
          subtitle="Bienvenue sur notre portail de partenariat"
          action="Devenir partenaire"
        ></Other_banner>
        <div className={styles.default_div}>
          Bienvenue sur notre portail de partenariat, Livraze est encore trop
          jeune, et est en quête de nouvelles collections pour subvenir aux
          besoins de ses lecteurs âgés à partir de 13 ans. Nous voulons avoir
          des rayons de livres plus éducatifs et riches en connaissances mais
          tout au début nous sommes heurtés à plusieurs difficultés entre autres
          :
          <ul>
            <li>
              Manque de moyens suffisants pour commander des livres à partir des
              librairies européens afin d’avoir des collections variées.
            </li>
            <li>
              Nous avons du mettre la pause sur l’accès aux élèves de 5, 6 et 7
              années par manques de collections qui cadre avec leur âge.
              Pourtant l’idée du départ de notre bibliothèque était de grandir
              en incitant les enfants de 8 à 17 ans d’avoir un accès aux livres
              pour enfant.
            </li>
            <li>
              En quête des partenaires qui nous aideront dans la plus grande
              mission que nous nous sommes fixer, celle d’inciter les jeunes à
              embrasser le monde de lecture.
            </li>
          </ul>
          <div>
            Voici comment vous pouvez nous aider :
            <Link href=""> Faites un Don à notre bibliothèque </Link>
          </div>
        </div>

        <Footer> </Footer>
        <Copyright> </Copyright>
      </main>
    </>
  );
}
