import Head from "next/head";
import Image from "next/image";
import Copyright from "../components/copyright";
import Footer from "../components/footer";
import Navbar from "../components/header";
import Other_banner from "@/components/soiree_cover";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Item_top_5 from "@/components/compsants_standards";
import List_items from "@/components/List_items";

const inter = Inter({ subsets: ["latin"] });

export default function partenariat() {
  return (
    <>
      <Head>
        <title>livraze </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo-livraze.png" />
      </Head>
      <main className={styles.main}>
        <Navbar></Navbar>
        <Other_banner
          title="Soirée littéraire"
          subtitle="des soirées qui reunissenr des esprits"
          action="procahaine soirée"
        ></Other_banner>
        <div className={styles.default_div}>
          <img src="/en.png" className={styles.justifyed_img} />
          <h1 className={styles.subtitle_n_sr}>
            {" "}
            Pourquoi une soirée littéraire ?
          </h1>
          <p>
            Afin de promouvoir la littérature locale et nationale, Livraze s'est
            donné pour mission d'organiser des cercles littéraires autour des
            livres des auteurs congolais de la diaspora ou vivant au pays. Les
            soirées de Livraze sont festives et elles réunissent des auteurs
            nationaux devant un public d'étudiants, d'entrepreneurs, d'avocats,
            de médecins, d'enseignants, de commerçants... pour échanger et se
            rencontrer autour de l'actualité du livre mais de manière vivante en
            compagnie d'un auteur local ou national. Les cercles littéraires de
            Livraze font rêver et réunissent des auteurs nationaux devant un
            public d'étudiants, d'entrepreneurs, d'avocats, de médecins,
            d'enseignants, de commerçants... afin d'échanger, de se rencontrer
            autour de l'actualité du livre mais de manière vivante.
          </p>
          <h1 className={styles.subtitle_n}>
            {" "}
            3 heures, un livre, un auteur, une culture à découvrir{" "}
          </h1>
          <p>
            {" "}
            Les soirées littéraires de la bibliothèque Livraze sont organisées
            de manière à valoriser les auteurs congolais, à promouvoir leurs
            œuvres afin d'encourager la génération montante à embrasser le monde
            des lettres. Nos cercles littéraires sont décorés et aménagés avec
            le meilleur soin artistique afin de permettre aux participants de
            découvrir non seulement les livres mais aussi tout un éventail de
            cultures congolaises.
          </p>
          <ul>
            <li>
              La gastronomie congolaise : Nous invitons des chefs experts en
              gastronomie congolaise qui nous feront déguster des menus
              congolais.
            </li>
            <li>
              Musique congolaise/Slam : Nous sélectionnons des musiciens,
              pianistes, guitaristes lors de nos soirées littéraires pour nous
              replonger au centre de la culture de notre grand pays.
            </li>
            <li>
              Peinture : Nous exposons des tableaux aux créativités
              exceptionnelles réalisés par des peintres locaux ou nationaux afin
              de valoriser la culture congolaise à travers la peinture.
            </li>
            <li>
              Photographie : Nous retraçons les souvenirs de nos soirées grâce
              au support photographique de nos partenaires photographes afin de
              garder en mémoire chaque moment de nos soirées.
            </li>
            <li>
              Cinéma : Nous invitons des cinéastes locaux et nationaux à nous
              parler du cinéma congolais.
            </li>
          </ul>
          <br />{" "}
          <div className={styles.call_to_action_n}>
            <a href=""> Voir la prochaine soirée → </a>
          </div>
        </div>

        <Footer> </Footer>
        <Copyright> </Copyright>
      </main>
    </>
  );
}
