import Head from "next/head";
import Image from "next/image";
import Copyright from "../components/copyright";
import Footer from "../components/footer";
import Navbar from "../components/header";
import Other_banner from "@/components/soiree_cover";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Item_top_5 from "@/components/compsants_standards";
import List_items from "@/components/List_items";
import Nav_bar from "../components/navbar";
import Link from "next/link";

// const inter = Inter({ subsets: ["latin"] });

export default function partenariat() {
  return (
    <>
      <Head>
        <title>livraze </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo-livraze.png" />
      </Head>
      <main className={styles.main}>
        <Navbar />
        <Other_banner
          title="Soirée littéraire"
          subtitle="des soirées qui reunissent des esprits"
        ></Other_banner>
        <div className={styles.default_div}>
          <div className="intro_soiree_container_details">
            <div className="section_img"></div>
            <div className="section_text">
              <div className="DATE">
                <div className="jour">
                  18
                  <div className="mois">janvier</div>{" "}
                </div>{" "}
              </div>
              <h2>
                Soirée <span className="text_coloric">Littéraire</span>
                <span className="dot">.</span>
              </h2>
              <h5>
                Sous le Thème <b>Safari !</b>
              </h5>
              Afin de promouvoir la littérature locale et nationale, Livraze
              s'est donné pour mission d'organiser des cercles littéraires
              autour des livres des auteurs congolais de la diaspora ou vivant
              au pays. Les soirées de Livraze sont festives et elles réunissent
              des auteurs nationaux devant un public d'étudiants,
              d'entrepreneurs, d'avocats, de médecins, d'enseignants, de
              commerçants... <br />
            </div>
          </div>
          <h3 className="">Programmes soirées littéraires</h3>
          <p>
            Nos soirées littéraires ont lieu{" "}
            <i> une fois par mois de 15h45 à 18h55.</i>
          </p>
          <p>15h45 - 16h45 : Accueil et cocktail (Gastronomie Congolaise)</p>
          <p>
            16h45 - 17h45 : Un livre, un auteur, Rencontre avec un auteur :
            discussions et échanges autour de son œuvre.
          </p>
          <p>
            17h45 - 17h55 : Musique live en lien avec l'univers de l'auteur.
          </p>
          <p>
            17h55 - 18h25 : Expositions (photographes, dessinateurs, peintres et
            cinéastes)
          </p>
          <p>
            18h25 - 18h35 : Témoignages de librairies et bibliothèques
            universitaires ou indépendantes
          </p>
          <p>
            18h35 - 18h55 : Networking et signature des livres de l'auteur
            autour d'un verre.
          </p>
          18h55 : Clôture de l'activité <br />
          <div className="call_to_action">
            <Link href="">Participer à la soirée →</Link>
          </div>
        </div>

        <Footer> </Footer>
        <Copyright> </Copyright>
      </main>
    </>
  );
}
