import Head from "next/head";
import Image from "next/image";
import Copyright from "../components/copyright";
import Footer from "../components/footer";
import Navbar from "../components/header";
import Other_banner from "@/components/soiree_cover";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Item_top_5 from "@/components/compsants_standards";
import List_items from "@/components/List_items";
import Nav_bar from "../components/navbar";
import Link from "next/link";
import Carousel from "react-bootstrap/Carousel";

// const inter = Inter({ subsets: ["latin"] });

export default function partenariat() {
  return (
    <>
      <Head>
        <title>livraze </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo-livraze.png" />
      </Head>
      <main className={styles.main}>
        <Navbar />
        <Other_banner
          title="Soirée littéraire"
          subtitle="des soirées qui reunissent des esprits"
        ></Other_banner>
        <div className={styles.default_divs}>
          <div className="intro_soiree_container_details">
            <div className="section_img">
              <div className="carousse_soiree">
                <Carousel
                  fade
                  indicators={false}
                  prevIcon={false}
                  nextIcon={false}
                >
                  <Carousel.Item>
                    <img
                      className="d-block w-100"
                      src="1livr.png"
                      alt="First slide"
                    />
                    <Carousel.Caption></Carousel.Caption>
                  </Carousel.Item>
                  <Carousel.Item>
                    <img
                      className="d-block w-100"
                      src="gastronomie.png"
                      alt="Second slide"
                    />

                    <Carousel.Caption></Carousel.Caption>
                  </Carousel.Item>
                  <Carousel.Item>
                    <img
                      className="d-block w-100"
                      src="2livr.png"
                      alt="Third slide"
                    />
                  </Carousel.Item>
                </Carousel>
              </div>
            </div>
            <div className="section_text">
              {/* <div className="DATE">
                <div className="jour">
                  18
                  <div className="mois">janvier</div>{" "}
                </div>{" "}
              </div> */}
              <h2>
                Soirée <span className="text_coloric">Littéraire</span>
                <span className="dot">.</span>
              </h2>
              <h3>
                La première soirée Littéraire de Livraze autour du livre :{" "}
                <b>Créer son entreprise sans argent.</b>
              </h3>
              Aujourd’hui, comme dans plusieurs villes de la RDC, les jeunes
              s’intéressent à l’entrepreneuriat mais peu sont ceux qui se
              lancent malgré les contraintes financières. Ce guide de poche pour
              l’entrepreneur va nous permettre de prendre ce choix au sérieux et
              de se focaliser sur son projet. Pendant la présentation de ce
              livre par l’auteur, vous aurez mille et une raisons d’embrasser le
              domaine entrepreneurial.
              <br />
              <h5>Biographie de l’auteur :</h5>
              Dr. Yves Daniel L.
              <br /> Ngavan Master en Développement Organisationnel ( Université
              Laval-Québec-Canada), Spécialiste Senior en Gestion des ressources
              Humaines et Coach en Entrepreneuriat avec plus de 12 ans
              d’expérience professionnelle.
              <br /> Consultant-Formateur en Management des projets, suivi et
              évaluation auprès des ONG et programmes de coopérations
              internationales.
              <h5> A la découverte de la Culture Rega : </h5> Les Lega sont une
              population forestière bantoue d'Afrique centrale, établie
              principalement en République démocratique du Congo (RDC), à l'Est
              du fleuve Lwalaba (le fleuve Congo), jusqu'en altitude dans les
              monts Mitumba, dans les provinces du Nord-Kivu, du Sud-Kivu et du
              Maniema. Le totem des Lega est le pangolin. <br /> Nous allons en
              plus découvrir la GASTRONOMIE REGA…
              <h5>Slam : </h5> Entreprendre, Fonder sa boite, engager la
              jeunesse, continuer à rêver grand pour nos communautés. Pendant la
              soirée, nous serons amenés à la découverte de l’art de la musique
              par Franck Amir, clameur, écrivain et poète.
              <h5>Peinture : </h5> Chaque culture a ses couleurs, Découvrez les
              tableaux magnifiques peints par D. Bolton qui vont surement vous
              envoyer dans le profondeur de vos souvenirs.
            </div>
          </div>
          <h3 className="">Programmes soirées littéraires</h3>
          <p>
            Nos soirées littéraires ont lieu{" "}
            <i> une fois par mois de 15h45 à 18h55.</i>
          </p>
          <p>
            15h45 - 16h45 : Accueil et cocktail Gastronomie Rega avec Maison
            Traiteur{" "}
          </p>
          <p>
            16h45 - 17h45 : UDiscussions et échanges autour du Livre Comment
            créer une entreprise sans argent du Dr. Yves Daniel.
          </p>
          <p>17h45 - 17h55 : Musique/Slam avec Franck Amak.</p>
          <p>
            17h55 - 18h25 : Expositions (photographes, dessinateurs, peintres et
            cinéastes)
          </p>
          <p>18h25 - 18h35 : Expositions Dessin avec D. Blton</p>
          <p>
            18h35 - 18h55 : Networking autour d'un verre. 18h55 : Clôture de
            l'activité
          </p>
          <br />
          <div className="call_to_action ">
            <Link href="#">Participer à la soirée →</Link>
          </div>
        </div>

        <Footer> </Footer>
        <Copyright> </Copyright>
      </main>
    </>
  );
}
