import Head from "next/head";
import Image from "next/image";
import Nav_bar from "../components/navbar";
import Copyright from "../components/copyright";
import Footer from "../components/footer";
import Navbar from "../components/header";
import Other_banner from "@/components/other_banner";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Item_top_5 from "@/components/compsants_standards";
import List_items from "@/components/List_items";
import { useState, useEffect } from "react";
import Carte_pour_livre from "@/components/collection_congolaise";
import { post } from "jquery";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>livraze </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo-livraze.png" />
      </Head>
      <Navbar />

      <main className={styles.main}>
        <Other_banner
          title="Profitez de l'abonnement !"
          subtitle="AFIN D'ACCÉDER À NOS COLLECTIONS"
        ></Other_banner>
        <div className={styles.pricingtable}>
          <div className={styles.container}>
            <div className={`${styles["element"]} ${styles["prix_1"]}`}>
              {" "}
              {/* class=" prix_1" */}
              <div className={styles.info}>
                <h3>
                  {" "}
                  <b> Etudiant </b>
                </h3>
                <p>
                  {" "}
                  vous pouvez accéder à la bibliothèque livraze pour une{" "}
                  <b>lecture de 2 ouvrages</b> avec la possibilité d'emprunter 1
                  ouvrage pour une lecture à domicile{" "}
                </p>
              </div>
              <span className={styles.price}>4.6$/mois</span>
              <Link href="../etudiant">
                <button className={styles.btn_1}>S'abonner</button>
              </Link>
            </div>
            <div className={`${styles["element"]} ${styles["prix_2"]}`}>
              {" "}
              {/* prix_2 */}
              <div className={styles.info}>
                <h3>
                  {" "}
                  <b>Premium </b>
                </h3>
                <p>
                  Vous pouvez acceder à la bibliothèque livraze pour une{" "}
                  <b>lecture de 5 ouvrages</b> avec la possibilité d'emprunter 2
                  de ces 3 ouvrages pour une lecture à domicile <br /> Profitez
                  egalement de 50% de réduction sur le tarif de participation à
                  nos soirées littéraires
                </p>
              </div>
              <span className={styles.price}>11,99$/mois</span>
              <Link href="../premium">
                <button className={styles.btn_2}>S'abonner</button>
              </Link>
            </div>
            <div className={`${styles["element"]} ${styles["prix_3"]}`}>
              {/* prix_3 */}
              <div className={styles.info}>
                <h3>
                  <b>Standard</b>
                </h3>
                <p>
                  vous pouvez acceder à la bibliothèque livraze pour une{" "}
                  <b>lecture de 3 ouvrages</b> avec la possibilité d'emprunter 1
                  de ces 3 ouvrages pour une lecture à domicile
                </p>
              </div>
              <span className={styles.price}>9.99$/mois</span>
              <Link href="../standard">
                <button className={styles.btn_3}>S'abonner</button>
              </Link>
            </div>
          </div>
        </div>
        <Footer> </Footer>
        <Copyright> </Copyright>
      </main>
    </>
  );
}
